(in-package :scorer)

(defun current-date ()
    (multiple-value-bind (sec min hr day mnt year) (get-decoded-time)
      (list `(:sec . ,sec)
	    `(:min . ,min)
	    `(:hour . ,hr)
	    `(:day . ,day)
	    `(:month . ,mnt)
	    `(:year . ,year))))

(defun today ()
  (let ((lst (current-date)))
    (list (assoc :year  lst)
	  (assoc :month lst)
	  (assoc :day   lst))))
